dataset:
    train_data_dir: new_train.pkl
    test_data_dir: new_test.pkl


model:
    seq_length : 5000
    patch_size : 20
    in_chans : 1
    embed_dim : 768
    hidden_dim: 768
    ntoken: 3621
    d_model: 768
    nhead: 8
    d_hid: 512
    nlayers: 6


loss_names:
    vf: 1
    mofid: 1
    xrd: 0
    regression: 0
    classification: 0



seed: 0
num_nodes: 1
model_path:
visualize: False
test: False
per_gpu_batchsize: 16
batch_size: 256
resume_from: 
learning_rate: 0.0001
weight_decay: 0.01
lr_mult: 1
end_lr: 0
decay_power: 1
optim_type: adamw
warmup_steps: 0.05


vf_mean: 0.5038
vf_std: 0.2057


resume_from: 
