dataset:
    train_data_dir: /home/users/seunghh/data_mining/exit/new_data_mofid/train.pkl
    test_data_dir: /home/users/seunghh/data_mining/exit/new_data_mofid/test.pkl




model:
    seq_length : 4500
    patch_size : 20
    in_chans : 1
    embed_dim : 768
    hidden_dim: 768
    ntoken: 4021
    d_model: 768
    nhead: 8
    d_hid: 512
    nlayers: 6


loss_names:
    sa: 1
    pv: 1
    mofid: 1
    regression: 0
    classification: 0


seed: 0
num_nodes: 1
model_path:
visualize: False
test: False
per_gpu_batchsize: 8
batch_size: 128
resume_from: 
learning_rate: 0.0001
weight_decay: 0.01
lr_mult: 1
end_lr: 0
decay_power: 1
optim_type: adamw
warmup_steps: 0.05

pv_mean: 1.3282
pv_std: 1.1354
sa_mean: 2562.1021
sa_std: 1170.1410

resume_from: 
