dataset:
    train_data_dir: /home/users/seunghh/data_mining/exit/data/hmof_ch4/train.pkl
    valid_data_dir: /home/users/seunghh/data_mining/exit/data/hmof_ch4/valid.pkl
    test_data_dir: /home/users/seunghh/data_mining/exit/data/hmof_ch4/test.pkl




model:
    seq_length : 4500
    patch_size : 20
    in_chans : 1
    embed_dim : 768
    hidden_dim: 768
    ntoken: 1086
    d_model: 768
    nhead: 8
    d_hid: 512
    nlayers: 6


loss_names:
    sa: 0
    pv: 0
    mofid: 0
    regression: 1
    classification: 0


seed: 0
num_nodes: 1
visualize: False
test: False
per_gpu_batchsize: 16
batch_size: 16
resume_from: 
learning_rate: 0.0001
weight_decay: 0.01
lr_mult: 1
end_lr: 0
decay_power: 1
optim_type: adamw
warmup_steps: 0.05

regression_mean: 0.8447
regression_std: 0.6597
